address review feedback
Signed-off-by: Xin Li <xin.li@hedera.com>

diff --git a/.github/workflows/auto-release.yml b/.github/workflows/auto-release.yml
--- a/.github/workflows/auto-release.yml
+++ b/.github/workflows/auto-release.yml
@@ -11,10 +11,6 @@ on:
       chartVersion:
         description: 'Chart Version'
         required: true
-      preReleaseIdentifier:
-        description: 'PreRelease Identifier, e.g., alpha1, rc1'
-        required: true
-        default: 'rc1'
 
 jobs:
   release:
@@ -23,40 +19,45 @@ jobs:
       CHANGELOG: CHANGELOG.md
       RELEASE_NOTES_FILENAME: release_notes
       RELEASE_NOTES_FULLNAME: release_notes.md
+      SEMVER_REGEX: '(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?'
 
     steps:
-      - name: Get Version
+      - name: Get Version from Milestone
+        if: ${{ github.event_name == 'milestone' }}
         run: |
-          EVENT_NAME="${{ github.event_name }}"
-          case "$EVENT_NAME" in
-            "milestone" )
-              TITLE="${{ github.event.milestone.title }}"
-              [[ "$TITLE" =~ (([0-9]*\.){2}[0-9]*) ]] || { echo "Invalid milestone title $TITLE"; exit 1; }
-              RELEASE_VERSION=${BASH_REMATCH}
-              ;;
-            "workflow_dispatch" )
-              RELEASE_VERSION="${{ github.event.inputs.version }}-${{ github.event.inputs.preReleaseIdentifier }}"
-              ;;
-            *)
-              echo "Unsupported event_name $EVENT_NAME"
-              exit 1
-            ;;
-          esac
+          TITLE="${{ github.event.milestone.title }}"
+          [[ "$TITLE" =~ $SEMVER_REGEX ]] || { echo "Invalid milestone title $TITLE"; exit 1; }
+          RELEASE_VERSION=${BASH_REMATCH}
+          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
 
-          [[ "$RELEASE_VERSION" =~ ([0-9]*\.[0-9]*)\.[0-9]* ]] || { echo "Invalid version ${RELEASE_VERSION}"; exit 1; }
-          RELEASE_BRANCH="release/${BASH_REMATCH[1]}"
+      - name: Get Version from Workflow Dispatch Input
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        run: echo RELEASE_VERSION="${{ github.event.inputs.version }}" >> $GITHUB_ENV
+
+      - name: Parse Version
+        id: release_semver
+        uses: apexskier/github-semver-parse@v1
+        with:
+          version: ${{ env.RELEASE_VERSION }}
+
+      - name: Set Release Environment Variables
+        run: |
+          [[ -z "${{ steps.release_semver.outputs.version }}" ]] && { echo "Invalid version"; exit 1; }
+          RELEASE_BRANCH="release/${{ steps.release_semver.outputs.major }}.${{ steps.release_semver.outputs.minor }}"
           RELEASE_TAG=v${RELEASE_VERSION}
+          RELEASE_VERSION_NEXT_MINOR=$((${{ steps.release_semver.outputs.minor }}+1))
+          RELEASE_VERSION_NEXT_SNAPSHOT="${{ steps.release_semver.outputs.major }}.${RELEASE_VERSION_NEXT_MINOR}.0-SNAPSHOT"
 
           echo "RELEASE_BRANCH=${RELEASE_BRANCH}" >> $GITHUB_ENV
           echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
-          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
+          echo "RELEASE_VERSION_NEXT_SNAPSHOT=${RELEASE_VERSION_NEXT_SNAPSHOT}" >> $GITHUB_ENV
 
       - name: Checkout Repository
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      - name: Cache Maven packages
+      - name: Cache Maven Packages
         uses: actions/cache@v2
         with:
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
@@ -75,7 +76,7 @@ jobs:
       - name: Get Chart Version from Workflow Dispatch Input
         if: ${{ github.event_name == 'workflow_dispatch' }}
         run: |
-          CHART_VERSION="${{ github.event.inputs.chartVersion }}-${{ github.event.inputs.preReleaseIdentifier}}"
+          CHART_VERSION="${{ github.event.inputs.chartVersion }}"
           echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV
 
       - name: Get Chart Version from Release Branch
@@ -83,6 +84,26 @@ jobs:
         run: |
           CHART_VERSION=$(sed -rn 's/<release\.chartVersion>([0-9.]*).*<\/release.chartVersion>/\1/p' pom.xml | xargs)
           echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV
+
+      - name: Parse Chart Version
+        id: chart_semver
+        uses: apexskier/github-semver-parse@v1
+        with:
+          version: ${{ env.CHART_VERSION }}
+
+      - name: Set Chart Version for Patch Release
+        if: ${{ steps.release_semver.outputs.patch != 0 && steps.chart_semver.outputs.prerelease == '' }}
+        run: |
+          CHART_VERSION_PATCH=$((${{ steps.chart_semver.outputs.patch }}+1))
+          CHART_VERSION="${{ steps.chart_semver.outputs.major }}.${{ steps.chart_semver.outputs.minor }}.${CHART_VERSION_PATCH}"
+          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV
+
+      - name: Set Next Chart Snapshot Version
+        run: |
+          [[ -z "${{ steps.chart_semver.outputs.version }}" ]] && { echo "Invalid chart version"; exit 1; }
+          CHART_VERSION_NEXT_MINOR=$((${{ steps.chart_semver.outputs.minor }}+1))
+          CHART_VERSION_NEXT_SNAPSHOT="${{ steps.chart_semver.outputs.major }}.${CHART_VERSION_NEXT_MINOR}.0-SNAPSHOT"
+          echo "CHART_VERSION_NEXT_SNAPSHOT=${CHART_VERSION_NEXT_SNAPSHOT}" >> $GITHUB_ENV
 
       - name: Update Pom
         run: |
@@ -102,17 +123,37 @@ jobs:
       - name: Update Changelog
         if: ${{ github.event_name == 'milestone' }}
         run: |
+          DESCRIPTION="${{ github.event.milestone.description }}"
           RELEASE_DATE=$(date +%Y-%m-%d)
-          TMPFILE=$(mktemp --suffix .md)
-          cp $CHANGELOG $TMPFILE
-          echo -e "# ${RELEASE_DATE} ${RELEASE_VERSION}\n" > $CHANGELOG
-          cat $RELEASE_NOTES_FULLNAME $TMPFILE >> $CHANGELOG
-          rm -f $TMPFILE
+
+          GITHUB_RELEASE_NOTES=$(mktemp --suffix .md)
+          TMP_CHANGELOG=$(mktemp --suffix .md)
+          TMP_RELEASE_NOTES=$(mktemp --suffix .md)
+
+          # copy to a temporary file for modification due to lack of write permsision
+          if [ ! -z "$DESCRIPTION" ]; then
+            echo -e "$DESCRIPTION\n" > $GITHUB_RELEASE_NOTES
+            cat $RELEASE_NOTES_FULLNAME >> $GITHUB_RELEASE_NOTES
+          else
+            cp $RELEASE_NOTES_FULLNAME $GITHUB_RELEASE_NOTES
+          fi
+          sed -r 's/^(#+) /\1# /g' $GITHUB_RELEASE_NOTES > $TMP_RELEASE_NOTES
+
+          FIRST_LINE=$(grep -E -n -m 1 "^## ${SEMVER_REGEX}" $CHANGELOG | cut -d: -f1)
+          FIRST_LINE=${FIRST_LINE:-1}
+          tail -n +${FIRST_LINE} $CHANGELOG > $TMP_CHANGELOG
+          echo -e "# Hedera Mirror Node Changelog\n" > $CHANGELOG
+          echo -e "## ${RELEASE_VERSION} (${RELEASE_DATE})\n" >> $CHANGELOG
+          cat $TMP_RELEASE_NOTES >> $CHANGELOG
+          echo "" >> $CHANGELOG
+          cat $TMP_CHANGELOG >> $CHANGELOG
+
+          echo "GITHUB_RELEASE_NOTES=${GITHUB_RELEASE_NOTES}" >> $GITHUB_ENV
 
       - name: Commit and Tag
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
-          commit_message: Bump version to ${{ env.RELEASE_VERSION }}
+          commit_message: Bump version to ${{ env.RELEASE_TAG }}
           commit_options: '--no-verify --signoff'
           tagging_message: ${{ env.RELEASE_TAG }}
 
@@ -121,6 +162,14 @@ jobs:
           git checkout master
           git reset --hard ${RELEASE_BRANCH}
 
+      - name: Update Version to Next Minor Snapshot
+        run: |
+          sed -i -r -e 's/(<release\.version>).*(<\/release\.version>)/\1'${RELEASE_VERSION_NEXT_SNAPSHOT}'\2/g' \
+            -e 's/(<release\.chartVersion>).*(<\/release\.chartVersion>)/\1'${CHART_VERSION_NEXT_SNAPSHOT}'\2/g' pom.xml
+
+      - name: Maven Release for Next Minor Snapshot
+        run: ./mvnw clean package -N -P=release
+
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v3
         with:
@@ -128,16 +177,16 @@ jobs:
           branch: create-pull-request/${{ env.RELEASE_BRANCH }}
           delete-branch: true
           signoff: true
-          title: Merge version bump for ${{ env.RELEASE_VERSION }}
+          title: Bump version to v${{ env.RELEASE_VERSION_NEXT_SNAPSHOT }} and merge changes from ${{ env.RELEASE_BRANCH }}
 
       - name: Create Github Release
         uses: ncipollo/release-action@v1
         with:
-          bodyFile: ${{ env.RELEASE_NOTES_FULLNAME }}
+          bodyFile: ${{ env.GITHUB_RELEASE_NOTES }}
           commit: ${{ env.RELEASE_BRANCH }}
-          draft: ${{ github.event_name == 'milestone' }}
+          draft: true
           name: ${{ env.RELEASE_TAG }}
           omitBody: ${{ github.event_name == 'workflow_dispatch' }}
-          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
+          prerelease: ${{ steps.release_semver.outputs.prerelease != '' }}
           tag: ${{ env.RELEASE_TAG }}
           token: ${{ secrets.GITHUB_TOKEN }}
